# Generated by Django 3.0.6 on 2021-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=15)),
                ('expiry', models.DateField()),
                ('cvv', models.CharField(max_length=5)),
                ('zip', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
