# Generated by Django 3.0.6 on 2021-05-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry',
            field=models.CharField(max_length=10),
        ),
    ]
