# Generated by Django 3.0.6 on 2021-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210518_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='zip',
        ),
    ]
