# Generated by Django 3.0.6 on 2021-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210518_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
